keys:
  - &perihelie_perikon age14truh9xkelz4perud6chaz9ejpmjfny0rkz69lr84zrnjqlx89psha6eex
  - &perikon age107mf2xs77yseuaelwnvr8kuk6xygxznlrmdmqfsa0tz2uhd4pafs22n9dp
  - &airhelie age1x0at9d9kj9nc5huys45zc34r5hfpm6hgxxcnvmh5jh4j70ucmpsqzkrvke
  - &periserver age1a8wy7xq8xs7l00vkq7ehtp5dupal08u588xjxedyaw5c39ju8umsmxh8v0

creation_rules:
  - path_regex: modules/hosts/perikon/secrets\.yaml$
    key_groups:
      - age:
          - *perikon
  - path_regex: modules/hosts/periserver/modules/secrets\.yaml$
    key_groups:
      - age:
          - *periserver
  - path_regex: modules/hosts/airhelie/secrets\.yaml$
    key_groups:
      - age:
          - *airhelie
  - path_regex: modules/users/perihelie/perihelie_secrets\.yaml$
    key_groups:
      - age:
          - *perihelie_perikon
          - *airhelie
          - *periserver
